[platformio]
extra_configs = secrets.ini

[env:wokwi]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_flags =
    -std=gnu++23
    -Wno-deprecated-declarations
    -DCORE_DEBUG_LEVEL=1
build_unflags = -std=gnu++11
monitor_speed = 115200
lib_deps =
    blues/Blues Wireless Notecard
    note-emu=symlink://../../
lib_ldf_mode = chain

[env:hardware]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.36/platform-espressif32.zip
board = esp32-s3-devkitm-1
framework = arduino
board_upload.after_reset = watchdog-reset
build_flags =
    -std=gnu++23
    -Wno-deprecated-declarations
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_unflags = -std=gnu++11
monitor_speed = 115200
lib_deps =
    blues/Blues Wireless Notecard
    note-emu=symlink://../../
lib_ldf_mode = chain
