[env:wokwi]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
build_flags =
    -std=gnu++23
    -Wno-deprecated-declarations
    -DCORE_DEBUG_LEVEL=1
build_unflags = -std=gnu++11
monitor_speed = 115200
lib_deps =
    note-emu=symlink://../../
    note-cpp=symlink://${sysenv.HOME}/e/note-cpp
lib_ldf_mode = chain
